export const IconList = [
    { id: 1, name: 'ad', svg: '/ressources/icon-svg/AD.svg' },
    { id: 2, name: 'add', svg: '/ressources/icon-svg/Add.svg' },
    { id: 3, name: 'apple', svg: '/ressources/icon-svg/apple.svg' },
    { id: 4, name: 'chevron-down', svg: '/ressources/icon-svg/chevron-down.svg' },
    { id: 5, name: 'comment', svg: '/ressources/icon-svg/Comment.svg' },
    { id: 6, name: 'credit-card', svg: '/ressources/icon-svg/Credit card.svg' },
    { id: 7, name: 'hd', svg: '/ressources/icon-svg/HD.svg' },
    { id: 8, name: 'info', svg: '/ressources/icon-svg/info.svg' },
    { id: 9, name: 'lock', svg: '/ressources/icon-svg/lock.svg' },
    { id: 10, name: 'login', svg: '/ressources/icon-svg/login.svg' },
    { id: 11, name: 'notify', svg: '/ressources/icon-svg/Notify.svg' },
    { id: 12, name: 'player-play', svg: '/ressources/icon-svg/player-play.svg' },
    { id: 13, name: 'playstore', svg: '/ressources/icon-svg/playstore.svg' },
    { id: 14, name: 'search', svg: '/ressources/icon-svg/Search.svg' },
    { id: 15, name: 'settings', svg: '/ressources/icon-svg/settings.svg' },
    { id: 16, name: 'symbol-sms', svg: '/ressources/icon-svg/Symbol-sms.svg' },
    { id: 17, name: 'user', svg: '/ressources/icon-svg/User.svg' },
    { id: 18, name: 'bonus', svg: '/ressources/icon-svg/bonus.svg' },
    { id: 19, name: 'plus', svg: '/ressources/icon-svg/plus.svg' },
    { id: 20, name: 'volume-mute', svg: '/ressources/icon-svg/volume-mute.svg' },
    { id: 21, name: 'bonus', svg: '/ressources/icon-svg/bonus.svg' },
    { id: 22, name: 'facebook', svg: '/ressources/icon-svg/facebook.svg' },
    { id: 23, name: 'instagram', svg: '/ressources/icon-svg/instagram.svg' },
    { id: 24, name: 'linkedin', svg: '/ressources/icon-svg/linkedin.svg' },
    { id: 25, name: 'twitter', svg: '/ressources/icon-svg/twitter.svg' },
    { id: 26, name: 'youtube', svg: '/ressources/icon-svg/youtube.svg' },
    { id: 27, name: 'plus', svg: '/ressources/icon-svg/plus.svg' },
    { id: 28, name: 'share', svg: '/ressources/icon-svg/share.svg' },
    { id: 28, name: 'tiktok', svg: '/ressources/icon-svg/img.svg' },
]